### ISSUE TITLE
Are you planning to support to CppADCodegen

### ISSUE THREAD

**Issue by cmastalli** [bradbell/cppad_py#10]
Hi all,

I just noticed this repository, and thank you so much for making this effort.
I would like to know if the team of developers are planning to support `CppADCodeGen` in future.

It would be great to have such kind of tool :)

Yours,
Carlos

PD: is `pycppad` a deprecated repository?

**Comment by bradbell** [comment]
I am no longer supporting pycppad. I changed over to using swig instead of boost-python to communicate between CppAD and python (so that it would be easy for others to do other languages and for other reasons).

I have a lot of  wish list items to work on and do not think I will make a CppADCodeGen connection to cppad_py anytime in the near future.

**Comment by cmastalli** [comment]
Thank you for the prompt response!
